name: Build and Push Docker Image

on:
  push:
    branches: [main]
    paths-ignore:
      - "**.md"
      - ".gitignore"
      - "LICENSE"
  pull_request:
    branches: [main]
  workflow_dispatch:

env:
  DOCKER_HUB_REPO: amgadabdelhafez/publicrepo

jobs:
  build-and-push:
    runs-on: ubuntu-22.04 # Explicitly use ubuntu-22.04 instead of latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3 # Updated to v3

      - name: Set up Python
        uses: actions/setup-python@v4 # Add Python setup
        with:
          python-version: "3.8" # Match Dockerfile Python version

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # Updated to v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3 # Updated to v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Get current date for tag
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT

      # Get short SHA
      - name: Get short SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v5 # Updated to v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ${{ env.DOCKER_HUB_REPO }}:latest
            ${{ env.DOCKER_HUB_REPO }}:${{ steps.date.outputs.date }}-${{ steps.sha.outputs.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
